var annotated_dup =
[
    [ "ScrapGameEngine", null, [
      [ "AllocatedTexture", "struct_scrap_game_engine_1_1_allocated_texture.html", "struct_scrap_game_engine_1_1_allocated_texture" ],
      [ "Application", "class_scrap_game_engine_1_1_application.html", "class_scrap_game_engine_1_1_application" ],
      [ "AppWindow", "class_scrap_game_engine_1_1_app_window.html", "class_scrap_game_engine_1_1_app_window" ],
      [ "AppWindowData", "struct_scrap_game_engine_1_1_app_window_data.html", "struct_scrap_game_engine_1_1_app_window_data" ],
      [ "AudioSource", "class_scrap_game_engine_1_1_audio_source.html", "class_scrap_game_engine_1_1_audio_source" ],
      [ "BaseComponent", "class_scrap_game_engine_1_1_base_component.html", "class_scrap_game_engine_1_1_base_component" ],
      [ "BaseScene", "class_scrap_game_engine_1_1_base_scene.html", "class_scrap_game_engine_1_1_base_scene" ],
      [ "Button", "class_scrap_game_engine_1_1_button.html", "class_scrap_game_engine_1_1_button" ],
      [ "Camera", "class_scrap_game_engine_1_1_camera.html", "class_scrap_game_engine_1_1_camera" ],
      [ "CameraConfig", "struct_scrap_game_engine_1_1_camera_config.html", "struct_scrap_game_engine_1_1_camera_config" ],
      [ "DrawCommand", "struct_scrap_game_engine_1_1_draw_command.html", "struct_scrap_game_engine_1_1_draw_command" ],
      [ "GameObject", "class_scrap_game_engine_1_1_game_object.html", "class_scrap_game_engine_1_1_game_object" ],
      [ "GameObjectCollection", "class_scrap_game_engine_1_1_game_object_collection.html", "class_scrap_game_engine_1_1_game_object_collection" ],
      [ "Glyph", "struct_scrap_game_engine_1_1_glyph.html", "struct_scrap_game_engine_1_1_glyph" ],
      [ "Graphics", "class_scrap_game_engine_1_1_graphics.html", "class_scrap_game_engine_1_1_graphics" ],
      [ "Input", "class_scrap_game_engine_1_1_input.html", null ],
      [ "IResourceManager", "class_scrap_game_engine_1_1_i_resource_manager.html", null ],
      [ "Mesh", "class_scrap_game_engine_1_1_mesh.html", "class_scrap_game_engine_1_1_mesh" ],
      [ "MeshAllocator", "class_scrap_game_engine_1_1_mesh_allocator.html", null ],
      [ "Renderer", "class_scrap_game_engine_1_1_renderer.html", null ],
      [ "RenderParams", "struct_scrap_game_engine_1_1_render_params.html", "struct_scrap_game_engine_1_1_render_params" ],
      [ "ResourceManagementSystem", "class_scrap_game_engine_1_1_resource_management_system.html", null ],
      [ "SceneStateMachine", "class_scrap_game_engine_1_1_scene_state_machine.html", "class_scrap_game_engine_1_1_scene_state_machine" ],
      [ "Scheduler", "class_scrap_game_engine_1_1_scheduler.html", null ],
      [ "SpriteRenderer", "class_scrap_game_engine_1_1_sprite_renderer.html", "class_scrap_game_engine_1_1_sprite_renderer" ],
      [ "Text", "class_scrap_game_engine_1_1_text.html", "class_scrap_game_engine_1_1_text" ],
      [ "Texture2D", "class_scrap_game_engine_1_1_texture2_d.html", "class_scrap_game_engine_1_1_texture2_d" ],
      [ "TextureAllocator", "class_scrap_game_engine_1_1_texture_allocator.html", "class_scrap_game_engine_1_1_texture_allocator" ],
      [ "TextureConfig", "struct_scrap_game_engine_1_1_texture_config.html", "struct_scrap_game_engine_1_1_texture_config" ],
      [ "Transform", "class_scrap_game_engine_1_1_transform.html", "class_scrap_game_engine_1_1_transform" ],
      [ "TweenComponent", "class_scrap_game_engine_1_1_tween_component.html", "class_scrap_game_engine_1_1_tween_component" ],
      [ "Vertex", "struct_scrap_game_engine_1_1_vertex.html", "struct_scrap_game_engine_1_1_vertex" ]
    ] ],
    [ "GameScene", "class_game_scene.html", "class_game_scene" ],
    [ "HoverSensor", "class_hover_sensor.html", "class_hover_sensor" ],
    [ "LoadScene", "class_load_scene.html", "class_load_scene" ],
    [ "MainMenuScene", "class_main_menu_scene.html", "class_main_menu_scene" ],
    [ "Signal", "class_signal.html", "class_signal" ],
    [ "SplashScreenScene", "class_splash_screen_scene.html", "class_splash_screen_scene" ]
];