#pragma once

#include "rhi/Buffer.h"
#include "rhi/VertexArray.h"

#include <glm/glm.hpp>

#include <memory>
#include <string>
#include <vector>

namespace ScrapGameEngine
{
    /**
     * @struct MeshVertex
     * @brief One vertex of a 3D mesh.
     *
     * Tangents are stored alongside the normal so normal mapping needs no second pass
     * over the data later; they cost 12 bytes and are computed once at load.
     */
    struct MeshVertex
    {
        glm::vec3 position{0.0f};
        glm::vec3 normal{0.0f, 0.0f, 1.0f};
        glm::vec2 uv{0.0f};
        glm::vec3 tangent{1.0f, 0.0f, 0.0f};
    };

    /**
     * @class Mesh3D
     * @brief Indexed triangle geometry on the GPU.
     *
     * Distinct from the 2D path on purpose: sprites are generated by the batcher and
     * never own buffers, whereas a mesh is uploaded once and drawn many times.
     */
    class Mesh3D
    {
    public:
        Mesh3D() = default;

        Mesh3D(const Mesh3D&) = delete;
        Mesh3D& operator=(const Mesh3D&) = delete;

        /** @brief Uploads vertices and indices, replacing anything already held. */
        bool create(const std::vector<MeshVertex>& vertices,
                    const std::vector<uint32_t>& indices);

        void bind() const { vao.bind(); }
        unsigned int getIndexCount() const { return indexCount; }
        bool isValid() const { return indexCount > 0; }

        const std::string& getName() const { return name; }
        void setName(std::string value) { name = std::move(value); }

        // --- primitives, so a scene can be built before any importer exists -----

        /** @brief A unit cube centred on the origin, with per-face normals. */
        static std::shared_ptr<Mesh3D> createCube();

        /** @brief A UV sphere of unit radius. */
        static std::shared_ptr<Mesh3D> createSphere(int segments = 32, int rings = 16);

        /** @brief A flat plane on XZ, facing +Y. */
        static std::shared_ptr<Mesh3D> createPlane(float size = 1.0f);

    private:
        VertexArray vao;
        VertexBuffer vbo;
        IndexBuffer ibo;
        unsigned int indexCount = 0;
        std::string name = "Mesh";
    };
}
